language: java

install:
- mvn install -B -V

deploy:
  - provider: elasticbeanstalk
    skip_cleanup: true
    zip_file: 'dropwizard-example-1.2.1-SNAPSHOT-assembly.zip'
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key:
      secure: $AWS_SECRET_ACCESS_KEY
    region: "eu-west-2"
    app: "template"
    env: "Template-env"
    bucket_name: "elasticbeanstalk-eu-west-2-437443739767"
    on:
      all_branches: true

